# Generated by Django 6.0 on 2026-05-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='name',
            new_name='nome',
        ),
    ]
